### ISSUE TITLE
I'm getting this error while trying to view datastore entriess

### ISSUE THREAD

**Issue by ccuser44** [jlwitthuhn/OpenCloudTools#2]
I'm getting this error while trying to view datastore entries
`
Sending request...
Error, response did not contain userids
`

**Comment by jlwitthuhn** [comment]
Thanks for the report, this is fixed in commit 6a801b0b02ced45fc8c34af2e63d469cf098af49

[Release 20220605.0](https://github.com/jlwitthuhn/OpenCloudTools/releases/tag/v20220605.0) includes this fix.
