### ISSUE TITLE
Can't close modals

### ISSUE THREAD

**Issue by jackTabsCode** [jlwitthuhn/OpenCloudTools#5]
In the latest release, opening a modal (such as viewing data from a key) opens it, but there is no way to close it. The program must be force quit. This is occurring on macOS Sequoia.

<img width="1363" alt="image" src="https://github.com/user-attachments/assets/67109184-bdbb-4ae2-ba7f-1bb8eb37b4b9">

**Comment by jlwitthuhn** [comment]
Thanks for the report, I haven't tested this super-thoroughly on mac but it looks like the title bar is missing for some reason even though it shows up on windows. Ideally that window should be closable with the 'x' button like any other.

This is probably an unintended side-effect of me recently switching those dialogs from being 'Application Modal' to just 'Window Modal', which appears to have some unique behavior on macos.

Checking it out now, hope to have a fix ready and released by some time this weekend.

**Comment by jackTabsCode** [comment]
Thanks for the swift response.

**Comment by jlwitthuhn** [comment]
Just pushed a commit here that I think should fix it: https://github.com/jlwitthuhn/OpenCloudTools/commit/6e8b939ca58ae528ff6a56ee9b55fcc00a5924aa

Still need to do some testing to make sure I didn't break something else, but I should be able to get a release together in the next day or two.

**Comment by jlwitthuhn** [comment]
Added a new release here, everything should now be fixed on MacOS.

https://github.com/jlwitthuhn/OpenCloudTools/releases/tag/v2024.09.15.0
